/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticRouteRouteImport } from './routes/(static)/route'
import { Route as TenantRouteRouteImport } from './routes/$tenant/route'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as LoginTenantRouteImport } from './routes/login.$tenant'
import { Route as staticServicesRouteImport } from './routes/(static)/services'
import { Route as TenantAdminRouteImport } from './routes/$tenant/admin'
import { Route as TenantTransactionRouteRouteImport } from './routes/$tenant/transaction/route'
import { Route as TenantReportRouteRouteImport } from './routes/$tenant/report/route'
import { Route as TenantInventoryRouteRouteImport } from './routes/$tenant/inventory/route'
import { Route as TenantExpensesRouteRouteImport } from './routes/$tenant/expenses/route'
import { Route as TenantCashierRouteRouteImport } from './routes/$tenant/cashier/route'
import { Route as TenantSupplierIndexRouteImport } from './routes/$tenant/supplier/index'
import { Route as TenantReportIndexRouteImport } from './routes/$tenant/report/index'
import { Route as TenantCashierIndexRouteImport } from './routes/$tenant/cashier/index'
import { Route as TenantReportSalesRouteImport } from './routes/$tenant/report/sales'
import { Route as TenantReportPurchasesRouteImport } from './routes/$tenant/report/purchases'
import { Route as TenantInventoryStockRouteImport } from './routes/$tenant/inventory/stock'
import { Route as TenantInventoryProductsRouteImport } from './routes/$tenant/inventory/products'
import { Route as TenantInventoryCreateProductRouteImport } from './routes/$tenant/inventory/create-product'
import { Route as TenantInventoryCategoryRouteImport } from './routes/$tenant/inventory/category'
import { Route as TenantExpensesPurchaseRouteImport } from './routes/$tenant/expenses/purchase'
import { Route as TenantExpensesOperationalRouteImport } from './routes/$tenant/expenses/operational'
import { Route as TenantCashierTodayRouteImport } from './routes/$tenant/cashier/today'
import { Route as TenantTransactionSalesIndexRouteImport } from './routes/$tenant/transaction/sales.index'
import { Route as TenantTransactionPurchasesIndexRouteImport } from './routes/$tenant/transaction/purchases.index'
import { Route as TenantTransactionSalesArchieveRouteImport } from './routes/$tenant/transaction/sales.archieve'
import { Route as TenantTransactionPurchasesArchieveRouteImport } from './routes/$tenant/transaction/purchases.archieve'
import { Route as TenantSupplierHistoryIdRouteImport } from './routes/$tenant/supplier/history.$id'
import { Route as TenantCashierEditOrderIdRouteImport } from './routes/$tenant/cashier/edit.$orderId'

const staticRouteRoute = staticRouteRouteImport.update({
  id: '/(static)',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIndexRoute = staticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => staticRouteRoute,
} as any)
const LoginTenantRoute = LoginTenantRouteImport.update({
  id: '/login/$tenant',
  path: '/login/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const staticServicesRoute = staticServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => staticRouteRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantTransactionRouteRoute = TenantTransactionRouteRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantReportRouteRoute = TenantReportRouteRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantInventoryRouteRoute = TenantInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantExpensesRouteRoute = TenantExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCashierRouteRoute = TenantCashierRouteRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantSupplierIndexRoute = TenantSupplierIndexRouteImport.update({
  id: '/supplier/',
  path: '/supplier/',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantReportIndexRoute = TenantReportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantReportRouteRoute,
} as any)
const TenantCashierIndexRoute = TenantCashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantCashierRouteRoute,
} as any)
const TenantReportSalesRoute = TenantReportSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TenantReportRouteRoute,
} as any)
const TenantReportPurchasesRoute = TenantReportPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => TenantReportRouteRoute,
} as any)
const TenantInventoryStockRoute = TenantInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantInventoryProductsRoute = TenantInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantInventoryCreateProductRoute =
  TenantInventoryCreateProductRouteImport.update({
    id: '/create-product',
    path: '/create-product',
    getParentRoute: () => TenantInventoryRouteRoute,
  } as any)
const TenantInventoryCategoryRoute = TenantInventoryCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantExpensesPurchaseRoute = TenantExpensesPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => TenantExpensesRouteRoute,
} as any)
const TenantExpensesOperationalRoute =
  TenantExpensesOperationalRouteImport.update({
    id: '/operational',
    path: '/operational',
    getParentRoute: () => TenantExpensesRouteRoute,
  } as any)
const TenantCashierTodayRoute = TenantCashierTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => TenantCashierRouteRoute,
} as any)
const TenantTransactionSalesIndexRoute =
  TenantTransactionSalesIndexRouteImport.update({
    id: '/sales/',
    path: '/sales/',
    getParentRoute: () => TenantTransactionRouteRoute,
  } as any)
const TenantTransactionPurchasesIndexRoute =
  TenantTransactionPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => TenantTransactionRouteRoute,
  } as any)
const TenantTransactionSalesArchieveRoute =
  TenantTransactionSalesArchieveRouteImport.update({
    id: '/sales/archieve',
    path: '/sales/archieve',
    getParentRoute: () => TenantTransactionRouteRoute,
  } as any)
const TenantTransactionPurchasesArchieveRoute =
  TenantTransactionPurchasesArchieveRouteImport.update({
    id: '/purchases/archieve',
    path: '/purchases/archieve',
    getParentRoute: () => TenantTransactionRouteRoute,
  } as any)
const TenantSupplierHistoryIdRoute = TenantSupplierHistoryIdRouteImport.update({
  id: '/supplier/history/$id',
  path: '/supplier/history/$id',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCashierEditOrderIdRoute =
  TenantCashierEditOrderIdRouteImport.update({
    id: '/edit/$orderId',
    path: '/edit/$orderId',
    getParentRoute: () => TenantCashierRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/$tenant/cashier': typeof TenantCashierRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/report': typeof TenantReportRouteRouteWithChildren
  '/$tenant/transaction': typeof TenantTransactionRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/report/purchases': typeof TenantReportPurchasesRoute
  '/$tenant/report/sales': typeof TenantReportSalesRoute
  '/$tenant/cashier/': typeof TenantCashierIndexRoute
  '/$tenant/report/': typeof TenantReportIndexRoute
  '/$tenant/supplier/': typeof TenantSupplierIndexRoute
  '/$tenant/cashier/edit/$orderId': typeof TenantCashierEditOrderIdRoute
  '/$tenant/supplier/history/$id': typeof TenantSupplierHistoryIdRoute
  '/$tenant/transaction/purchases/archieve': typeof TenantTransactionPurchasesArchieveRoute
  '/$tenant/transaction/sales/archieve': typeof TenantTransactionSalesArchieveRoute
  '/$tenant/transaction/purchases/': typeof TenantTransactionPurchasesIndexRoute
  '/$tenant/transaction/sales/': typeof TenantTransactionSalesIndexRoute
}
export interface FileRoutesByTo {
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/transaction': typeof TenantTransactionRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/report/purchases': typeof TenantReportPurchasesRoute
  '/$tenant/report/sales': typeof TenantReportSalesRoute
  '/$tenant/cashier': typeof TenantCashierIndexRoute
  '/$tenant/report': typeof TenantReportIndexRoute
  '/$tenant/supplier': typeof TenantSupplierIndexRoute
  '/$tenant/cashier/edit/$orderId': typeof TenantCashierEditOrderIdRoute
  '/$tenant/supplier/history/$id': typeof TenantSupplierHistoryIdRoute
  '/$tenant/transaction/purchases/archieve': typeof TenantTransactionPurchasesArchieveRoute
  '/$tenant/transaction/sales/archieve': typeof TenantTransactionSalesArchieveRoute
  '/$tenant/transaction/purchases': typeof TenantTransactionPurchasesIndexRoute
  '/$tenant/transaction/sales': typeof TenantTransactionSalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/(static)': typeof staticRouteRouteWithChildren
  '/$tenant/cashier': typeof TenantCashierRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/report': typeof TenantReportRouteRouteWithChildren
  '/$tenant/transaction': typeof TenantTransactionRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/(static)/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/(static)/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/report/purchases': typeof TenantReportPurchasesRoute
  '/$tenant/report/sales': typeof TenantReportSalesRoute
  '/$tenant/cashier/': typeof TenantCashierIndexRoute
  '/$tenant/report/': typeof TenantReportIndexRoute
  '/$tenant/supplier/': typeof TenantSupplierIndexRoute
  '/$tenant/cashier/edit/$orderId': typeof TenantCashierEditOrderIdRoute
  '/$tenant/supplier/history/$id': typeof TenantSupplierHistoryIdRoute
  '/$tenant/transaction/purchases/archieve': typeof TenantTransactionPurchasesArchieveRoute
  '/$tenant/transaction/sales/archieve': typeof TenantTransactionSalesArchieveRoute
  '/$tenant/transaction/purchases/': typeof TenantTransactionPurchasesIndexRoute
  '/$tenant/transaction/sales/': typeof TenantTransactionSalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$tenant'
    | '/$tenant/cashier'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/report'
    | '/$tenant/transaction'
    | '/$tenant/admin'
    | '/services'
    | '/login/$tenant'
    | '/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/report/purchases'
    | '/$tenant/report/sales'
    | '/$tenant/cashier/'
    | '/$tenant/report/'
    | '/$tenant/supplier/'
    | '/$tenant/cashier/edit/$orderId'
    | '/$tenant/supplier/history/$id'
    | '/$tenant/transaction/purchases/archieve'
    | '/$tenant/transaction/sales/archieve'
    | '/$tenant/transaction/purchases/'
    | '/$tenant/transaction/sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$tenant'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/transaction'
    | '/$tenant/admin'
    | '/services'
    | '/login/$tenant'
    | '/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/report/purchases'
    | '/$tenant/report/sales'
    | '/$tenant/cashier'
    | '/$tenant/report'
    | '/$tenant/supplier'
    | '/$tenant/cashier/edit/$orderId'
    | '/$tenant/supplier/history/$id'
    | '/$tenant/transaction/purchases/archieve'
    | '/$tenant/transaction/sales/archieve'
    | '/$tenant/transaction/purchases'
    | '/$tenant/transaction/sales'
  id:
    | '__root__'
    | '/$tenant'
    | '/(static)'
    | '/$tenant/cashier'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/report'
    | '/$tenant/transaction'
    | '/$tenant/admin'
    | '/(static)/services'
    | '/login/$tenant'
    | '/(static)/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/report/purchases'
    | '/$tenant/report/sales'
    | '/$tenant/cashier/'
    | '/$tenant/report/'
    | '/$tenant/supplier/'
    | '/$tenant/cashier/edit/$orderId'
    | '/$tenant/supplier/history/$id'
    | '/$tenant/transaction/purchases/archieve'
    | '/$tenant/transaction/sales/archieve'
    | '/$tenant/transaction/purchases/'
    | '/$tenant/transaction/sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  staticRouteRoute: typeof staticRouteRouteWithChildren
  LoginTenantRoute: typeof LoginTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)': {
      id: '/(static)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof staticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof staticRouteRoute
    }
    '/login/$tenant': {
      id: '/login/$tenant'
      path: '/login/$tenant'
      fullPath: '/login/$tenant'
      preLoaderRoute: typeof LoginTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/services': {
      id: '/(static)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof staticServicesRouteImport
      parentRoute: typeof staticRouteRoute
    }
    '/$tenant/admin': {
      id: '/$tenant/admin'
      path: '/admin'
      fullPath: '/$tenant/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/transaction': {
      id: '/$tenant/transaction'
      path: '/transaction'
      fullPath: '/$tenant/transaction'
      preLoaderRoute: typeof TenantTransactionRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/report': {
      id: '/$tenant/report'
      path: '/report'
      fullPath: '/$tenant/report'
      preLoaderRoute: typeof TenantReportRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/inventory': {
      id: '/$tenant/inventory'
      path: '/inventory'
      fullPath: '/$tenant/inventory'
      preLoaderRoute: typeof TenantInventoryRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/expenses': {
      id: '/$tenant/expenses'
      path: '/expenses'
      fullPath: '/$tenant/expenses'
      preLoaderRoute: typeof TenantExpensesRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/cashier': {
      id: '/$tenant/cashier'
      path: '/cashier'
      fullPath: '/$tenant/cashier'
      preLoaderRoute: typeof TenantCashierRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/supplier/': {
      id: '/$tenant/supplier/'
      path: '/supplier'
      fullPath: '/$tenant/supplier/'
      preLoaderRoute: typeof TenantSupplierIndexRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/report/': {
      id: '/$tenant/report/'
      path: '/'
      fullPath: '/$tenant/report/'
      preLoaderRoute: typeof TenantReportIndexRouteImport
      parentRoute: typeof TenantReportRouteRoute
    }
    '/$tenant/cashier/': {
      id: '/$tenant/cashier/'
      path: '/'
      fullPath: '/$tenant/cashier/'
      preLoaderRoute: typeof TenantCashierIndexRouteImport
      parentRoute: typeof TenantCashierRouteRoute
    }
    '/$tenant/report/sales': {
      id: '/$tenant/report/sales'
      path: '/sales'
      fullPath: '/$tenant/report/sales'
      preLoaderRoute: typeof TenantReportSalesRouteImport
      parentRoute: typeof TenantReportRouteRoute
    }
    '/$tenant/report/purchases': {
      id: '/$tenant/report/purchases'
      path: '/purchases'
      fullPath: '/$tenant/report/purchases'
      preLoaderRoute: typeof TenantReportPurchasesRouteImport
      parentRoute: typeof TenantReportRouteRoute
    }
    '/$tenant/inventory/stock': {
      id: '/$tenant/inventory/stock'
      path: '/stock'
      fullPath: '/$tenant/inventory/stock'
      preLoaderRoute: typeof TenantInventoryStockRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/products': {
      id: '/$tenant/inventory/products'
      path: '/products'
      fullPath: '/$tenant/inventory/products'
      preLoaderRoute: typeof TenantInventoryProductsRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/create-product': {
      id: '/$tenant/inventory/create-product'
      path: '/create-product'
      fullPath: '/$tenant/inventory/create-product'
      preLoaderRoute: typeof TenantInventoryCreateProductRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/category': {
      id: '/$tenant/inventory/category'
      path: '/category'
      fullPath: '/$tenant/inventory/category'
      preLoaderRoute: typeof TenantInventoryCategoryRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/expenses/purchase': {
      id: '/$tenant/expenses/purchase'
      path: '/purchase'
      fullPath: '/$tenant/expenses/purchase'
      preLoaderRoute: typeof TenantExpensesPurchaseRouteImport
      parentRoute: typeof TenantExpensesRouteRoute
    }
    '/$tenant/expenses/operational': {
      id: '/$tenant/expenses/operational'
      path: '/operational'
      fullPath: '/$tenant/expenses/operational'
      preLoaderRoute: typeof TenantExpensesOperationalRouteImport
      parentRoute: typeof TenantExpensesRouteRoute
    }
    '/$tenant/cashier/today': {
      id: '/$tenant/cashier/today'
      path: '/today'
      fullPath: '/$tenant/cashier/today'
      preLoaderRoute: typeof TenantCashierTodayRouteImport
      parentRoute: typeof TenantCashierRouteRoute
    }
    '/$tenant/transaction/sales/': {
      id: '/$tenant/transaction/sales/'
      path: '/sales'
      fullPath: '/$tenant/transaction/sales/'
      preLoaderRoute: typeof TenantTransactionSalesIndexRouteImport
      parentRoute: typeof TenantTransactionRouteRoute
    }
    '/$tenant/transaction/purchases/': {
      id: '/$tenant/transaction/purchases/'
      path: '/purchases'
      fullPath: '/$tenant/transaction/purchases/'
      preLoaderRoute: typeof TenantTransactionPurchasesIndexRouteImport
      parentRoute: typeof TenantTransactionRouteRoute
    }
    '/$tenant/transaction/sales/archieve': {
      id: '/$tenant/transaction/sales/archieve'
      path: '/sales/archieve'
      fullPath: '/$tenant/transaction/sales/archieve'
      preLoaderRoute: typeof TenantTransactionSalesArchieveRouteImport
      parentRoute: typeof TenantTransactionRouteRoute
    }
    '/$tenant/transaction/purchases/archieve': {
      id: '/$tenant/transaction/purchases/archieve'
      path: '/purchases/archieve'
      fullPath: '/$tenant/transaction/purchases/archieve'
      preLoaderRoute: typeof TenantTransactionPurchasesArchieveRouteImport
      parentRoute: typeof TenantTransactionRouteRoute
    }
    '/$tenant/supplier/history/$id': {
      id: '/$tenant/supplier/history/$id'
      path: '/supplier/history/$id'
      fullPath: '/$tenant/supplier/history/$id'
      preLoaderRoute: typeof TenantSupplierHistoryIdRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/cashier/edit/$orderId': {
      id: '/$tenant/cashier/edit/$orderId'
      path: '/edit/$orderId'
      fullPath: '/$tenant/cashier/edit/$orderId'
      preLoaderRoute: typeof TenantCashierEditOrderIdRouteImport
      parentRoute: typeof TenantCashierRouteRoute
    }
  }
}

interface TenantCashierRouteRouteChildren {
  TenantCashierTodayRoute: typeof TenantCashierTodayRoute
  TenantCashierIndexRoute: typeof TenantCashierIndexRoute
  TenantCashierEditOrderIdRoute: typeof TenantCashierEditOrderIdRoute
}

const TenantCashierRouteRouteChildren: TenantCashierRouteRouteChildren = {
  TenantCashierTodayRoute: TenantCashierTodayRoute,
  TenantCashierIndexRoute: TenantCashierIndexRoute,
  TenantCashierEditOrderIdRoute: TenantCashierEditOrderIdRoute,
}

const TenantCashierRouteRouteWithChildren =
  TenantCashierRouteRoute._addFileChildren(TenantCashierRouteRouteChildren)

interface TenantExpensesRouteRouteChildren {
  TenantExpensesOperationalRoute: typeof TenantExpensesOperationalRoute
  TenantExpensesPurchaseRoute: typeof TenantExpensesPurchaseRoute
}

const TenantExpensesRouteRouteChildren: TenantExpensesRouteRouteChildren = {
  TenantExpensesOperationalRoute: TenantExpensesOperationalRoute,
  TenantExpensesPurchaseRoute: TenantExpensesPurchaseRoute,
}

const TenantExpensesRouteRouteWithChildren =
  TenantExpensesRouteRoute._addFileChildren(TenantExpensesRouteRouteChildren)

interface TenantInventoryRouteRouteChildren {
  TenantInventoryCategoryRoute: typeof TenantInventoryCategoryRoute
  TenantInventoryCreateProductRoute: typeof TenantInventoryCreateProductRoute
  TenantInventoryProductsRoute: typeof TenantInventoryProductsRoute
  TenantInventoryStockRoute: typeof TenantInventoryStockRoute
}

const TenantInventoryRouteRouteChildren: TenantInventoryRouteRouteChildren = {
  TenantInventoryCategoryRoute: TenantInventoryCategoryRoute,
  TenantInventoryCreateProductRoute: TenantInventoryCreateProductRoute,
  TenantInventoryProductsRoute: TenantInventoryProductsRoute,
  TenantInventoryStockRoute: TenantInventoryStockRoute,
}

const TenantInventoryRouteRouteWithChildren =
  TenantInventoryRouteRoute._addFileChildren(TenantInventoryRouteRouteChildren)

interface TenantReportRouteRouteChildren {
  TenantReportPurchasesRoute: typeof TenantReportPurchasesRoute
  TenantReportSalesRoute: typeof TenantReportSalesRoute
  TenantReportIndexRoute: typeof TenantReportIndexRoute
}

const TenantReportRouteRouteChildren: TenantReportRouteRouteChildren = {
  TenantReportPurchasesRoute: TenantReportPurchasesRoute,
  TenantReportSalesRoute: TenantReportSalesRoute,
  TenantReportIndexRoute: TenantReportIndexRoute,
}

const TenantReportRouteRouteWithChildren =
  TenantReportRouteRoute._addFileChildren(TenantReportRouteRouteChildren)

interface TenantTransactionRouteRouteChildren {
  TenantTransactionPurchasesArchieveRoute: typeof TenantTransactionPurchasesArchieveRoute
  TenantTransactionSalesArchieveRoute: typeof TenantTransactionSalesArchieveRoute
  TenantTransactionPurchasesIndexRoute: typeof TenantTransactionPurchasesIndexRoute
  TenantTransactionSalesIndexRoute: typeof TenantTransactionSalesIndexRoute
}

const TenantTransactionRouteRouteChildren: TenantTransactionRouteRouteChildren =
  {
    TenantTransactionPurchasesArchieveRoute:
      TenantTransactionPurchasesArchieveRoute,
    TenantTransactionSalesArchieveRoute: TenantTransactionSalesArchieveRoute,
    TenantTransactionPurchasesIndexRoute: TenantTransactionPurchasesIndexRoute,
    TenantTransactionSalesIndexRoute: TenantTransactionSalesIndexRoute,
  }

const TenantTransactionRouteRouteWithChildren =
  TenantTransactionRouteRoute._addFileChildren(
    TenantTransactionRouteRouteChildren,
  )

interface TenantRouteRouteChildren {
  TenantCashierRouteRoute: typeof TenantCashierRouteRouteWithChildren
  TenantExpensesRouteRoute: typeof TenantExpensesRouteRouteWithChildren
  TenantInventoryRouteRoute: typeof TenantInventoryRouteRouteWithChildren
  TenantReportRouteRoute: typeof TenantReportRouteRouteWithChildren
  TenantTransactionRouteRoute: typeof TenantTransactionRouteRouteWithChildren
  TenantAdminRoute: typeof TenantAdminRoute
  TenantSupplierIndexRoute: typeof TenantSupplierIndexRoute
  TenantSupplierHistoryIdRoute: typeof TenantSupplierHistoryIdRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantCashierRouteRoute: TenantCashierRouteRouteWithChildren,
  TenantExpensesRouteRoute: TenantExpensesRouteRouteWithChildren,
  TenantInventoryRouteRoute: TenantInventoryRouteRouteWithChildren,
  TenantReportRouteRoute: TenantReportRouteRouteWithChildren,
  TenantTransactionRouteRoute: TenantTransactionRouteRouteWithChildren,
  TenantAdminRoute: TenantAdminRoute,
  TenantSupplierIndexRoute: TenantSupplierIndexRoute,
  TenantSupplierHistoryIdRoute: TenantSupplierHistoryIdRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

interface staticRouteRouteChildren {
  staticServicesRoute: typeof staticServicesRoute
  staticIndexRoute: typeof staticIndexRoute
}

const staticRouteRouteChildren: staticRouteRouteChildren = {
  staticServicesRoute: staticServicesRoute,
  staticIndexRoute: staticIndexRoute,
}

const staticRouteRouteWithChildren = staticRouteRoute._addFileChildren(
  staticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TenantRouteRoute: TenantRouteRouteWithChildren,
  staticRouteRoute: staticRouteRouteWithChildren,
  LoginTenantRoute: LoginTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
