/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as staticRouteRouteImport } from './routes/(static)/route'
import { Route as TenantRouteRouteImport } from './routes/$tenant/route'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as LoginTenantRouteImport } from './routes/login.$tenant'
import { Route as staticServicesRouteImport } from './routes/(static)/services'
import { Route as TenantAdminRouteImport } from './routes/$tenant/admin'
import { Route as TenantInventoryRouteRouteImport } from './routes/$tenant/inventory/route'
import { Route as TenantExpensesRouteRouteImport } from './routes/$tenant/expenses/route'
import { Route as TenantCashierRouteRouteImport } from './routes/$tenant/cashier/route'
import { Route as TenantCashierIndexRouteImport } from './routes/$tenant/cashier/index'
import { Route as TenantInventoryStockRouteImport } from './routes/$tenant/inventory/stock'
import { Route as TenantInventoryProductsRouteImport } from './routes/$tenant/inventory/products'
import { Route as TenantInventoryCreateProductRouteImport } from './routes/$tenant/inventory/create-product'
import { Route as TenantInventoryCategoryRouteImport } from './routes/$tenant/inventory/category'
import { Route as TenantExpensesPurchaseRouteImport } from './routes/$tenant/expenses/purchase'
import { Route as TenantExpensesOperationalRouteImport } from './routes/$tenant/expenses/operational'
import { Route as TenantCashierTodayRouteImport } from './routes/$tenant/cashier/today'

const staticRouteRoute = staticRouteRouteImport.update({
  id: '/(static)',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRouteRoute = TenantRouteRouteImport.update({
  id: '/$tenant',
  path: '/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIndexRoute = staticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => staticRouteRoute,
} as any)
const LoginTenantRoute = LoginTenantRouteImport.update({
  id: '/login/$tenant',
  path: '/login/$tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const staticServicesRoute = staticServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => staticRouteRoute,
} as any)
const TenantAdminRoute = TenantAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantInventoryRouteRoute = TenantInventoryRouteRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantExpensesRouteRoute = TenantExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCashierRouteRoute = TenantCashierRouteRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => TenantRouteRoute,
} as any)
const TenantCashierIndexRoute = TenantCashierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantCashierRouteRoute,
} as any)
const TenantInventoryStockRoute = TenantInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantInventoryProductsRoute = TenantInventoryProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantInventoryCreateProductRoute =
  TenantInventoryCreateProductRouteImport.update({
    id: '/create-product',
    path: '/create-product',
    getParentRoute: () => TenantInventoryRouteRoute,
  } as any)
const TenantInventoryCategoryRoute = TenantInventoryCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => TenantInventoryRouteRoute,
} as any)
const TenantExpensesPurchaseRoute = TenantExpensesPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => TenantExpensesRouteRoute,
} as any)
const TenantExpensesOperationalRoute =
  TenantExpensesOperationalRouteImport.update({
    id: '/operational',
    path: '/operational',
    getParentRoute: () => TenantExpensesRouteRoute,
  } as any)
const TenantCashierTodayRoute = TenantCashierTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => TenantCashierRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/$tenant/cashier': typeof TenantCashierRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/cashier/': typeof TenantCashierIndexRoute
}
export interface FileRoutesByTo {
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/cashier': typeof TenantCashierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$tenant': typeof TenantRouteRouteWithChildren
  '/(static)': typeof staticRouteRouteWithChildren
  '/$tenant/cashier': typeof TenantCashierRouteRouteWithChildren
  '/$tenant/expenses': typeof TenantExpensesRouteRouteWithChildren
  '/$tenant/inventory': typeof TenantInventoryRouteRouteWithChildren
  '/$tenant/admin': typeof TenantAdminRoute
  '/(static)/services': typeof staticServicesRoute
  '/login/$tenant': typeof LoginTenantRoute
  '/(static)/': typeof staticIndexRoute
  '/$tenant/cashier/today': typeof TenantCashierTodayRoute
  '/$tenant/expenses/operational': typeof TenantExpensesOperationalRoute
  '/$tenant/expenses/purchase': typeof TenantExpensesPurchaseRoute
  '/$tenant/inventory/category': typeof TenantInventoryCategoryRoute
  '/$tenant/inventory/create-product': typeof TenantInventoryCreateProductRoute
  '/$tenant/inventory/products': typeof TenantInventoryProductsRoute
  '/$tenant/inventory/stock': typeof TenantInventoryStockRoute
  '/$tenant/cashier/': typeof TenantCashierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$tenant'
    | '/$tenant/cashier'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/admin'
    | '/services'
    | '/login/$tenant'
    | '/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/cashier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$tenant'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/admin'
    | '/services'
    | '/login/$tenant'
    | '/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/cashier'
  id:
    | '__root__'
    | '/$tenant'
    | '/(static)'
    | '/$tenant/cashier'
    | '/$tenant/expenses'
    | '/$tenant/inventory'
    | '/$tenant/admin'
    | '/(static)/services'
    | '/login/$tenant'
    | '/(static)/'
    | '/$tenant/cashier/today'
    | '/$tenant/expenses/operational'
    | '/$tenant/expenses/purchase'
    | '/$tenant/inventory/category'
    | '/$tenant/inventory/create-product'
    | '/$tenant/inventory/products'
    | '/$tenant/inventory/stock'
    | '/$tenant/cashier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TenantRouteRoute: typeof TenantRouteRouteWithChildren
  staticRouteRoute: typeof staticRouteRouteWithChildren
  LoginTenantRoute: typeof LoginTenantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(static)': {
      id: '/(static)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof staticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant': {
      id: '/$tenant'
      path: '/$tenant'
      fullPath: '/$tenant'
      preLoaderRoute: typeof TenantRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof staticRouteRoute
    }
    '/login/$tenant': {
      id: '/login/$tenant'
      path: '/login/$tenant'
      fullPath: '/login/$tenant'
      preLoaderRoute: typeof LoginTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/services': {
      id: '/(static)/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof staticServicesRouteImport
      parentRoute: typeof staticRouteRoute
    }
    '/$tenant/admin': {
      id: '/$tenant/admin'
      path: '/admin'
      fullPath: '/$tenant/admin'
      preLoaderRoute: typeof TenantAdminRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/inventory': {
      id: '/$tenant/inventory'
      path: '/inventory'
      fullPath: '/$tenant/inventory'
      preLoaderRoute: typeof TenantInventoryRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/expenses': {
      id: '/$tenant/expenses'
      path: '/expenses'
      fullPath: '/$tenant/expenses'
      preLoaderRoute: typeof TenantExpensesRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/cashier': {
      id: '/$tenant/cashier'
      path: '/cashier'
      fullPath: '/$tenant/cashier'
      preLoaderRoute: typeof TenantCashierRouteRouteImport
      parentRoute: typeof TenantRouteRoute
    }
    '/$tenant/cashier/': {
      id: '/$tenant/cashier/'
      path: '/'
      fullPath: '/$tenant/cashier/'
      preLoaderRoute: typeof TenantCashierIndexRouteImport
      parentRoute: typeof TenantCashierRouteRoute
    }
    '/$tenant/inventory/stock': {
      id: '/$tenant/inventory/stock'
      path: '/stock'
      fullPath: '/$tenant/inventory/stock'
      preLoaderRoute: typeof TenantInventoryStockRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/products': {
      id: '/$tenant/inventory/products'
      path: '/products'
      fullPath: '/$tenant/inventory/products'
      preLoaderRoute: typeof TenantInventoryProductsRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/create-product': {
      id: '/$tenant/inventory/create-product'
      path: '/create-product'
      fullPath: '/$tenant/inventory/create-product'
      preLoaderRoute: typeof TenantInventoryCreateProductRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/inventory/category': {
      id: '/$tenant/inventory/category'
      path: '/category'
      fullPath: '/$tenant/inventory/category'
      preLoaderRoute: typeof TenantInventoryCategoryRouteImport
      parentRoute: typeof TenantInventoryRouteRoute
    }
    '/$tenant/expenses/purchase': {
      id: '/$tenant/expenses/purchase'
      path: '/purchase'
      fullPath: '/$tenant/expenses/purchase'
      preLoaderRoute: typeof TenantExpensesPurchaseRouteImport
      parentRoute: typeof TenantExpensesRouteRoute
    }
    '/$tenant/expenses/operational': {
      id: '/$tenant/expenses/operational'
      path: '/operational'
      fullPath: '/$tenant/expenses/operational'
      preLoaderRoute: typeof TenantExpensesOperationalRouteImport
      parentRoute: typeof TenantExpensesRouteRoute
    }
    '/$tenant/cashier/today': {
      id: '/$tenant/cashier/today'
      path: '/today'
      fullPath: '/$tenant/cashier/today'
      preLoaderRoute: typeof TenantCashierTodayRouteImport
      parentRoute: typeof TenantCashierRouteRoute
    }
  }
}

interface TenantCashierRouteRouteChildren {
  TenantCashierTodayRoute: typeof TenantCashierTodayRoute
  TenantCashierIndexRoute: typeof TenantCashierIndexRoute
}

const TenantCashierRouteRouteChildren: TenantCashierRouteRouteChildren = {
  TenantCashierTodayRoute: TenantCashierTodayRoute,
  TenantCashierIndexRoute: TenantCashierIndexRoute,
}

const TenantCashierRouteRouteWithChildren =
  TenantCashierRouteRoute._addFileChildren(TenantCashierRouteRouteChildren)

interface TenantExpensesRouteRouteChildren {
  TenantExpensesOperationalRoute: typeof TenantExpensesOperationalRoute
  TenantExpensesPurchaseRoute: typeof TenantExpensesPurchaseRoute
}

const TenantExpensesRouteRouteChildren: TenantExpensesRouteRouteChildren = {
  TenantExpensesOperationalRoute: TenantExpensesOperationalRoute,
  TenantExpensesPurchaseRoute: TenantExpensesPurchaseRoute,
}

const TenantExpensesRouteRouteWithChildren =
  TenantExpensesRouteRoute._addFileChildren(TenantExpensesRouteRouteChildren)

interface TenantInventoryRouteRouteChildren {
  TenantInventoryCategoryRoute: typeof TenantInventoryCategoryRoute
  TenantInventoryCreateProductRoute: typeof TenantInventoryCreateProductRoute
  TenantInventoryProductsRoute: typeof TenantInventoryProductsRoute
  TenantInventoryStockRoute: typeof TenantInventoryStockRoute
}

const TenantInventoryRouteRouteChildren: TenantInventoryRouteRouteChildren = {
  TenantInventoryCategoryRoute: TenantInventoryCategoryRoute,
  TenantInventoryCreateProductRoute: TenantInventoryCreateProductRoute,
  TenantInventoryProductsRoute: TenantInventoryProductsRoute,
  TenantInventoryStockRoute: TenantInventoryStockRoute,
}

const TenantInventoryRouteRouteWithChildren =
  TenantInventoryRouteRoute._addFileChildren(TenantInventoryRouteRouteChildren)

interface TenantRouteRouteChildren {
  TenantCashierRouteRoute: typeof TenantCashierRouteRouteWithChildren
  TenantExpensesRouteRoute: typeof TenantExpensesRouteRouteWithChildren
  TenantInventoryRouteRoute: typeof TenantInventoryRouteRouteWithChildren
  TenantAdminRoute: typeof TenantAdminRoute
}

const TenantRouteRouteChildren: TenantRouteRouteChildren = {
  TenantCashierRouteRoute: TenantCashierRouteRouteWithChildren,
  TenantExpensesRouteRoute: TenantExpensesRouteRouteWithChildren,
  TenantInventoryRouteRoute: TenantInventoryRouteRouteWithChildren,
  TenantAdminRoute: TenantAdminRoute,
}

const TenantRouteRouteWithChildren = TenantRouteRoute._addFileChildren(
  TenantRouteRouteChildren,
)

interface staticRouteRouteChildren {
  staticServicesRoute: typeof staticServicesRoute
  staticIndexRoute: typeof staticIndexRoute
}

const staticRouteRouteChildren: staticRouteRouteChildren = {
  staticServicesRoute: staticServicesRoute,
  staticIndexRoute: staticIndexRoute,
}

const staticRouteRouteWithChildren = staticRouteRoute._addFileChildren(
  staticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TenantRouteRoute: TenantRouteRouteWithChildren,
  staticRouteRoute: staticRouteRouteWithChildren,
  LoginTenantRoute: LoginTenantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
